config/routes.rb
Shopy::Application.routes.draw do
  resources :orders

  resources :products

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :order_status, :payment, :shipping_address, :shipping_city, :customer_name, :customer_surname, presence: true, length: { maximum: 255 }
	
	has_many :line_items, dependent: :destroy
	has_many :products, through: :line_items
	
	accepts_nested_attributes_for :line_items, allow_destroy: true,
	:reject_if => lambda { |a| a[:product_id].blank? or a[:quantity].blank? or a[:price].blank? } 
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
	validates :description, :created_at, :manufacturer, :category, presence: true
	validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 } 
	
	has_many :line_items
	has_many :orders, through: :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_status, :payment, :shipping_address, :shipping_city, :customer_name, :customer_surname, 
      :line_items_attributes => [:id, :product_id, :quantity, :price, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :created_at, :manufacturer, :stock, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to_function(name, ("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/orders">Shopy</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/products">Products</a></li>
            <li><a href="/orders">Orders</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

		<%= yield %>

    </div>
</body>
</html>

app/views/line_items/_line_item.html.erb
<tr>
  <td><%= line_item.product.name %></td>
  <td><%= line_item.price %></td>
  <td><%= line_item.quantity %></td>
</tr>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_status %><br>
    <%= f.text_field :order_status %>
  </div>
  <div class="field">
    <%= f.label :payment %><br>
    <%= f.text_field :payment %>
  </div>
  <div class="field">
    <%= f.label :shipping_address %><br>
    <%= f.text_field :shipping_address %>
  </div>
  <div class="field">
    <%= f.label :shipping_city %><br>
    <%= f.text_field :shipping_city %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :customer_surname %><br>
    <%= f.text_field :customer_surname %>
  </div>
  
  <div class="line-items">
   <h2>Products</h2>
    
    <%= f.fields_for :line_items do |builder| %>
      <%= render "line_item_fields", f: builder %>
    <% end %>  

  </div>

  <%= link_to_add_fields "Add LineItem", f, :line_items %> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_line_item_fields.html.erb
<p class="line_item">
	<%= f.label :product, "Product" %>
	<%= f.collection_select :product_id, Product.all, :id, :name %>
	
	<%= f.label :quantity, "Quantity" %>
	<%= f.number_field :quantity %>

	<%= f.label :unit_price, "Price" %>
	<%= f.number_field :price %>

	<%= f.hidden_field :id %>
	<%= f.hidden_field :_destroy %>

	<%= link_to_function "Remove", "remove_line_item(this)" %>
</p>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Order status</th>
      <th>Payment</th>
      <th>Shipping address</th>
      <th>Shipping city</th>
      <th>Customer name</th>
      <th>Customer surname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_status %></td>
        <td><%= order.payment %></td>
        <td><%= order.shipping_address %></td>
        <td><%= order.shipping_city %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.customer_surname %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order status:</strong>
  <%= @order.order_status %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @order.payment %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>Shipping city:</strong>
  <%= @order.shipping_city %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Customer surname:</strong>
  <%= @order.customer_surname %>
</p>

<div class="Line Items">
	<h2>Line Items</h2>
	<table>
	  <tr>
	    <th>Product</th>
	    <th>Unit price</th>
	    <th>Quantity</th>
	  </tr>
	  <%= render @order.line_items %>
	</table> 
</div>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_area :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.text_field :stock %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created at</th>
      <th>Manufacturer</th>
      <th>Stock</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.created_at %></td>
        <td><%= product.manufacturer %></td>
        <td><%= product.stock %></td>
        <td><%= product.category %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @product.created_at %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @product.manufacturer %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>